language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.0
  - jruby-1.7.19
  - jruby-1.7.20
  - jruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-head
script:
  - bundle exec rspec
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.activesupport-edge
    - rvm: ruby-head
    - rvm: jruby-head
