language: ruby
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-1.7.26
  - jruby-9.1.9.0
  - jruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-head
script:
  - bundle exec rspec
before_install: 'gem install bundler -v 1.17'
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
    - rvm: ruby-head
    - rvm: jruby-head
